-- gen_pesq_db2.dbo.TB_DIM_USUARIO definition

-- Drop table

-- DROP TABLE gen_pesq_db2.dbo.TB_DIM_USUARIO;

CREATE TABLE gen_pesq_db2.dbo.TB_DIM_USUARIO (
	ID_REGUSR int IDENTITY(1,1) NOT NULL,
	NM_USUAID varchar(20) COLLATE Latin1_General_CI_AS NOT NULL,
	VL_PASSWD varchar(15) COLLATE Latin1_General_CI_AS NOT NULL,
	DT_REGCRI datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NOT NULL,
	VF_REGVAL bit DEFAULT 1 NOT NULL,
	CE_FUNCIO varchar(11) COLLATE Latin1_General_CI_AS NULL,
	DT_REGALT datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NULL,
	CD_MIGDAD int DEFAULT NULL NULL,
	CONSTRAINT PK__TB_DIM_U__EED04609CEB812C0 PRIMARY KEY (ID_REGUSR)
);


-- gen_pesq_db2.dbo.TB_META_COLUNAS definition

-- Drop table

-- DROP TABLE gen_pesq_db2.dbo.TB_META_COLUNAS;

CREATE TABLE gen_pesq_db2.dbo.TB_META_COLUNAS (
	ID_REGTBL int IDENTITY(1,1) NOT NULL,
	NM_TABELA varchar(16) COLLATE Latin1_General_CI_AS NOT NULL,
	NM_COLUNA varchar(9) COLLATE Latin1_General_CI_AS NOT NULL,
	NM_NOMETR varchar(30) COLLATE Latin1_General_CI_AS NOT NULL,
	DT_REGCRI datetime DEFAULT getdate() AT TIME ZONE 'E. South America Standard Time' NOT NULL,
	VF_REGVAL bit DEFAULT 1 NOT NULL,
	CD_MIGDAD int NULL,
	CONSTRAINT PK__TB_META___EC9203A7E1D4E487 PRIMARY KEY (ID_REGTBL)
);


-- gen_pesq_db2.dbo.TB_DIM_CARGO definition

-- Drop table

-- DROP TABLE gen_pesq_db2.dbo.TB_DIM_CARGO;

CREATE TABLE gen_pesq_db2.dbo.TB_DIM_CARGO (
	ID_REGCAR int IDENTITY(1,1) NOT NULL,
	NM_CARGO varchar(30) COLLATE Latin1_General_CI_AS NOT NULL,
	CD_CBO02 varchar(6) COLLATE Latin1_General_CI_AS NULL,
	CE_USUACR int NOT NULL,
	DT_REGCRI datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NOT NULL,
	VF_REGVAL bit DEFAULT 1 NOT NULL,
	CD_USUAAL int NULL,
	DT_REGALT datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NULL,
	CD_MIGDAD int NULL,
	CONSTRAINT PK__TB_DIM_C__D6C40CE6325E233F PRIMARY KEY (ID_REGCAR),
	CONSTRAINT CHE_CE_USUACR FOREIGN KEY (CE_USUACR) REFERENCES gen_pesq_db2.dbo.TB_DIM_USUARIO(ID_REGUSR)
);


-- gen_pesq_db2.dbo.TB_DIM_CLIENT definition

-- Drop table

-- DROP TABLE gen_pesq_db2.dbo.TB_DIM_CLIENT;

CREATE TABLE gen_pesq_db2.dbo.TB_DIM_CLIENT (
	ID_REGCLI int IDENTITY(1,1) NOT NULL,
	CP_CLIENT varchar(14) COLLATE Latin1_General_CI_AS NOT NULL,
	NM_CLIENT varchar(30) COLLATE Latin1_General_CI_AS NULL,
	CE_USUACR int NOT NULL,
	DT_REGCRI datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NOT NULL,
	VF_REGVAL bit DEFAULT 1 NOT NULL,
	CD_USUAAL int NULL,
	DT_REGALT datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NULL,
	CD_MIGDAD int NULL,
	CONSTRAINT PK__TB_DIM_C__D6C62C765EA293A7 PRIMARY KEY (ID_REGCLI),
	CONSTRAINT CHI_CE_USUACR FOREIGN KEY (CE_USUACR) REFERENCES gen_pesq_db2.dbo.TB_DIM_USUARIO(ID_REGUSR)
);


-- gen_pesq_db2.dbo.TB_DIM_DEPTO definition

-- Drop table

-- DROP TABLE gen_pesq_db2.dbo.TB_DIM_DEPTO;

CREATE TABLE gen_pesq_db2.dbo.TB_DIM_DEPTO (
	ID_REGDPT int IDENTITY(1,1) NOT NULL,
	NM_DEPTO varchar(20) COLLATE Latin1_General_CI_AS NOT NULL,
	CE_USUACR int NOT NULL,
	DT_REGCRI datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NOT NULL,
	VF_REGVAL bit DEFAULT 1 NOT NULL,
	CD_USUAAL int NULL,
	DT_REGALT datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NULL,
	CD_MIGDAD int NULL,
	CONSTRAINT PK__TB_DIM_D__DA7EBA06A0DF9CFD PRIMARY KEY (ID_REGDPT),
	CONSTRAINT CHA_CE_USUACR FOREIGN KEY (CE_USUACR) REFERENCES gen_pesq_db2.dbo.TB_DIM_USUARIO(ID_REGUSR)
);


-- gen_pesq_db2.dbo.TB_DIM_FILIAL definition

-- Drop table

-- DROP TABLE gen_pesq_db2.dbo.TB_DIM_FILIAL;

CREATE TABLE gen_pesq_db2.dbo.TB_DIM_FILIAL (
	ID_REGFIL int IDENTITY(1,1) NOT NULL,
	NM_FILIAL varchar(20) COLLATE Latin1_General_CI_AS NOT NULL,
	CE_USUACR int NOT NULL,
	DT_REGCRI datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NOT NULL,
	VF_REGVAL bit DEFAULT 1 NOT NULL,
	CD_USUAAL int NULL,
	DT_REGALT datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NULL,
	CD_MIGDAD int NULL,
	CONSTRAINT PK__TB_DIM_F__D9EE88B3780F3162 PRIMARY KEY (ID_REGFIL),
	CONSTRAINT CHB_CE_USUACR FOREIGN KEY (CE_USUACR) REFERENCES gen_pesq_db2.dbo.TB_DIM_USUARIO(ID_REGUSR)
);


-- gen_pesq_db2.dbo.TB_DIM_FUNCAO definition

-- Drop table

-- DROP TABLE gen_pesq_db2.dbo.TB_DIM_FUNCAO;

CREATE TABLE gen_pesq_db2.dbo.TB_DIM_FUNCAO (
	ID_REGFNC int IDENTITY(1,1) NOT NULL,
	NM_FUNCAO varchar(12) COLLATE Latin1_General_CI_AS NOT NULL,
	CE_USUACR int NOT NULL,
	DT_REGCRI datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NOT NULL,
	VF_REGVAL bit DEFAULT 1 NOT NULL,
	CD_USUAAL int NULL,
	DT_REGALT datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NULL,
	CD_MIGDAD int NULL,
	CONSTRAINT PK__TB_DIM_F__D9EF4FDCC48CEE85 PRIMARY KEY (ID_REGFNC),
	CONSTRAINT CHC_CE_USUACR FOREIGN KEY (CE_USUACR) REFERENCES gen_pesq_db2.dbo.TB_DIM_USUARIO(ID_REGUSR)
);


-- gen_pesq_db2.dbo.TB_DIM_IMPPES definition

-- Drop table

-- DROP TABLE gen_pesq_db2.dbo.TB_DIM_IMPPES;

CREATE TABLE gen_pesq_db2.dbo.TB_DIM_IMPPES (
	ID_REGINS int IDENTITY(1,1) NOT NULL,
	VL_INICIA float NULL,
	VL_FINAL float NULL,
	VL_ALIQU float NULL,
	CE_USUACR int NOT NULL,
	DT_REGCRI datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NOT NULL,
	VF_REGVAL bit DEFAULT 1 NOT NULL,
	CD_USUAAL int NULL,
	DT_REGALT datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NULL,
	NM_IMPOST varchar(5) COLLATE Latin1_General_CI_AS NULL,
	CD_MIGDAD int NULL,
	CONSTRAINT PK__TB_DIM_I__D8BADEE1CC747A17 PRIMARY KEY (ID_REGINS),
	CONSTRAINT CHK_CE_USUACR FOREIGN KEY (CE_USUACR) REFERENCES gen_pesq_db2.dbo.TB_DIM_USUARIO(ID_REGUSR)
);


-- gen_pesq_db2.dbo.TB_DIM_PRODUT definition

-- Drop table

-- DROP TABLE gen_pesq_db2.dbo.TB_DIM_PRODUT;

CREATE TABLE gen_pesq_db2.dbo.TB_DIM_PRODUT (
	ID_REGPRD int IDENTITY(1,1) NOT NULL,
	NM_PRODUT varchar(30) COLLATE Latin1_General_CI_AS NOT NULL,
	CD_NCM varchar(8) COLLATE Latin1_General_CI_AS NULL,
	VL_PIS float NOT NULL,
	VL_IPI float NOT NULL,
	CE_USUACR int NOT NULL,
	DT_REGCRI datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NOT NULL,
	VF_REGVAL bit DEFAULT 1 NOT NULL,
	CD_USUAAL int NULL,
	DT_REGALT datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NULL,
	VL_COFINS float NULL,
	CD_MIGDAD int NULL,
	VF_INSUMO bit NULL,
	CONSTRAINT PK__TB_DIM_P__DBE5B03D60BAAF99 PRIMARY KEY (ID_REGPRD),
	CONSTRAINT CHH_CE_USUACR FOREIGN KEY (CE_USUACR) REFERENCES gen_pesq_db2.dbo.TB_DIM_USUARIO(ID_REGUSR)
);


-- gen_pesq_db2.dbo.TB_DIM_SITFOL definition

-- Drop table

-- DROP TABLE gen_pesq_db2.dbo.TB_DIM_SITFOL;

CREATE TABLE gen_pesq_db2.dbo.TB_DIM_SITFOL (
	ID_REGSFL int IDENTITY(1,1) NOT NULL,
	DS_SITFOL varchar(12) COLLATE Latin1_General_CI_AS NOT NULL,
	CE_USUACR int NOT NULL,
	DT_REGCRI datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NOT NULL,
	VF_REGVAL bit DEFAULT 1 NOT NULL,
	CD_USUAAL int NULL,
	DT_REGALT datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NULL,
	CD_MIGDAD int NULL,
	CONSTRAINT PK__TB_DIM_S__DAA4D815E938DE7F PRIMARY KEY (ID_REGSFL),
	CONSTRAINT CHF_CE_USUACR FOREIGN KEY (CE_USUACR) REFERENCES gen_pesq_db2.dbo.TB_DIM_USUARIO(ID_REGUSR)
);


-- gen_pesq_db2.dbo.TB_FAT_SALFUN definition

-- Drop table

-- DROP TABLE gen_pesq_db2.dbo.TB_FAT_SALFUN;

CREATE TABLE gen_pesq_db2.dbo.TB_FAT_SALFUN (
	ID_REGSAL int IDENTITY(1,1) NOT NULL,
	CE_FUNCIO varchar(11) COLLATE Latin1_General_CI_AS NOT NULL,
	VL_SALARI decimal(8,2) NULL,
	CE_USUACR int NOT NULL,
	DT_REGCRI datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NOT NULL,
	VF_REGVAL bit DEFAULT 1 NOT NULL,
	CD_USUAAL int NULL,
	DT_REGALT datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NULL,
	CD_MIGDAD int NULL,
	CONSTRAINT PK__TB_FAT_S__DAA4C0FBE618DA2C PRIMARY KEY (ID_REGSAL),
	CONSTRAINT CHG_CE_USUACR FOREIGN KEY (CE_USUACR) REFERENCES gen_pesq_db2.dbo.TB_DIM_USUARIO(ID_REGUSR)
);


-- gen_pesq_db2.dbo.TB_FAT_VENDA definition

-- Drop table

-- DROP TABLE gen_pesq_db2.dbo.TB_FAT_VENDA;

CREATE TABLE gen_pesq_db2.dbo.TB_FAT_VENDA (
	ID_REGVEN int IDENTITY(1,1) NOT NULL,
	CE_CLIENT varchar(14) COLLATE Latin1_General_CI_AS NOT NULL,
	CE_PRODUT int NOT NULL,
	VL_VENDA decimal(8,2) NOT NULL,
	CE_USUACR int NOT NULL,
	DT_REGCRI datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NOT NULL,
	VF_REGVAL bit DEFAULT 1 NOT NULL,
	CD_USUAAL int NULL,
	DT_REGALT datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NULL,
	QT_VENDA int NOT NULL,
	CD_MIGDAD int NULL,
	CONSTRAINT PK__TB_FAT_V__EE12D2C7A3366357 PRIMARY KEY (ID_REGVEN),
	CONSTRAINT CHJ_CE_USUACR FOREIGN KEY (CE_USUACR) REFERENCES gen_pesq_db2.dbo.TB_DIM_USUARIO(ID_REGUSR)
);


-- gen_pesq_db2.dbo.TB_DIM_FUNCIO definition

-- Drop table

-- DROP TABLE gen_pesq_db2.dbo.TB_DIM_FUNCIO;

CREATE TABLE gen_pesq_db2.dbo.TB_DIM_FUNCIO (
	ID_REGFUN int IDENTITY(1,1) NOT NULL,
	CP_FUNCIO varchar(11) COLLATE Latin1_General_CI_AS NOT NULL,
	NM_FUNCIO varchar(30) COLLATE Latin1_General_CI_AS NOT NULL,
	DT_ADMISS varchar(8) COLLATE Latin1_General_CI_AS NOT NULL,
	CE_SITFOL int DEFAULT 1 NOT NULL,
	CE_CARGO int NOT NULL,
	CE_FUNCAO int NOT NULL,
	VL_DEPEND int NOT NULL,
	CE_FILIAL int NOT NULL,
	CE_DEPRTO int NOT NULL,
	CE_USUACR int NOT NULL,
	DT_REGCRI datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NOT NULL,
	VF_REGVAL bit DEFAULT 1 NOT NULL,
	CD_USUAAL int NULL,
	DT_REGALT datetime DEFAULT (getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'E. South America Standard Time' NULL,
	CD_MIGDAD int NULL,
	CONSTRAINT PK__TB_DIM_F__D9F3772A338DAF58 PRIMARY KEY (ID_REGFUN),
	CONSTRAINT CHA_CE_CARGO FOREIGN KEY (CE_FUNCAO) REFERENCES gen_pesq_db2.dbo.TB_DIM_FUNCAO(ID_REGFNC),
	CONSTRAINT CHA_CE_DEPRTO FOREIGN KEY (CE_DEPRTO) REFERENCES gen_pesq_db2.dbo.TB_DIM_DEPTO(ID_REGDPT),
	CONSTRAINT CHA_CE_FILIAL FOREIGN KEY (CE_FILIAL) REFERENCES gen_pesq_db2.dbo.TB_DIM_FILIAL(ID_REGFIL),
	CONSTRAINT CHA_CE_FUNCAO FOREIGN KEY (CE_FUNCAO) REFERENCES gen_pesq_db2.dbo.TB_DIM_FUNCAO(ID_REGFNC),
	CONSTRAINT CHA_CE_SITFOL FOREIGN KEY (CE_SITFOL) REFERENCES gen_pesq_db2.dbo.TB_DIM_SITFOL(ID_REGSFL),
	CONSTRAINT CHD_CE_USUACR FOREIGN KEY (CE_USUACR) REFERENCES gen_pesq_db2.dbo.TB_DIM_USUARIO(ID_REGUSR)
);
