-- DROP SCHEMA [MOD];

CREATE SCHEMA [MOD];
-- [MOD].VW_FUNCIONARIOS source

CREATE VIEW [MOD].[VW_FUNCIONARIOS]
AS
SELECT
    NM_FUNCIO AS Nome,
    CONCAT(SUBSTRING(CP_FUNCIO,1,3), '.', SUBSTRING(CP_FUNCIO, 4, 3), '.', SUBSTRING(CP_FUNCIO, 7, 3), '-', SUBSTRING(CP_FUNCIO, 10, 2)) AS CPF,
    FORMAT(CONVERT(date, DT_ADMISS), 'd', 'pt-br') AS [Dt Admis],
    DS_SITFOL AS [Sit Folha],
    NM_CARGO AS Cargo,
    NM_FUNCAO AS Funcao,
    VL_SALARI AS Salario,
    NM_FILIAL AS Filial,
    NM_DEPTO AS Depto,
    CP_FUNCIO AS CPF_PURO
FROM TB_DIM_FUNCIO
INNER JOIN TB_DIM_DEPTO ON CE_DEPRTO = ID_REGDPT
INNER JOIN TB_DIM_CARGO ON CE_CARGO = ID_REGCAR
INNER JOIN TB_DIM_FILIAL ON CE_FILIAL = ID_REGFIL
INNER JOIN TB_DIM_FUNCAO ON CE_FUNCAO = ID_REGFNC
INNER JOIN TB_DIM_SITFOL ON CE_SITFOL = ID_REGSFL
INNER JOIN TB_FAT_SALFUN ON CE_FUNCIO = CP_FUNCIO
WHERE
    TB_FAT_SALFUN.VF_REGVAL = 1 AND
    TB_DIM_FUNCIO.VF_REGVAL = 1;


-- [MOD].VW_FUNCIONARIOS_DETALHADO source

CREATE VIEW [MOD].[VW_FUNCIONARIOS_DETALHADO]
AS
SELECT 
	ID_REGFUN AS [ID Funcio],
	CP_FUNCIO AS [CPF Funcio],
	NM_FUNCIO AS [Nome Funcio],
	(SELECT TOP 1 NM_CARGO FROM TB_DIM_CARGO WHERE CE_CARGO = ID_REGCAR) AS [Cargo Funcio],
	(SELECT TOP 1 NM_FUNCAO FROM TB_DIM_FUNCAO WHERE CE_FUNCAO = ID_REGFNC) AS [Funcao Funcio],
	(SELECT TOP 1 VL_SALARI FROM TB_FAT_SALFUN WHERE CP_FUNCIO = CE_FUNCIO AND TB_FAT_SALFUN.VF_REGVAL = 1) AS [Salario Funcio],
	(SELECT TOP 1 NM_DEPTO FROM TB_DIM_DEPTO WHERE CE_DEPRTO = ID_REGDPT) AS [Depto Funcio],
	(SELECT TOP 1 NM_FILIAL FROM TB_DIM_FILIAL WHERE CE_FILIAL = ID_REGFIL) AS [Filial Funcio],
	VL_DEPEND AS [Dependentes],
	(SELECT TOP 1 DS_SITFOL FROM TB_DIM_SITFOL WHERE CE_SITFOL = ID_REGSFL) AS [Sit Funcio],
 	(SELECT TOP 1 VL_SALARI FROM TB_FAT_SALFUN WHERE CP_FUNCIO = CE_FUNCIO ORDER BY DT_REGCRI ASC) AS [Primeiro Salario Funcio],
	(SELECT TOP 1 ID_REGSAL FROM TB_FAT_SALFUN WHERE CP_FUNCIO = CE_FUNCIO AND TB_FAT_SALFUN.VF_REGVAL = 1) AS [ID Ult Mov Salarial],
	(SELECT TOP 1 TB_FAT_SALFUN.DT_REGCRI FROM TB_FAT_SALFUN WHERE CP_FUNCIO = CE_FUNCIO AND TB_FAT_SALFUN.VF_REGVAL = 1) AS [Data Ult Mov Salarial],
	(SELECT TOP 1 NM_USUAID FROM TB_DIM_USUARIO WHERE ID_REGUSR = FNC.CE_USUACR) AS [Usuario Criador],
	DT_REGCRI AS [Data Criacao],
	(SELECT TOP 1 NM_USUAID FROM TB_DIM_USUARIO WHERE ID_REGUSR = FNC.CD_USUAAL) AS [Ult Usuario Alterador],
	DT_REGALT AS [Ult Data Altera]
FROM TB_DIM_FUNCIO FNC
WHERE FNC.VF_REGVAL = 1;


-- [MOD].VW_FUNCIONARIOS_excel source

CREATE VIEW [MOD].[VW_FUNCIONARIOS_excel]
AS
SELECT
	ID_REGFUN AS [ID],
    NM_FUNCIO AS Nome,
    CONCAT(SUBSTRING(CP_FUNCIO,1,3), '.', SUBSTRING(CP_FUNCIO, 4, 3), '.', SUBSTRING(CP_FUNCIO, 7, 3), '-', SUBSTRING(CP_FUNCIO, 10, 2)) AS CPF,
    FORMAT(CONVERT(date, DT_ADMISS), 'd', 'pt-br') AS [Dt Admis],
    DS_SITFOL AS [Sit Folha],
    NM_CARGO AS Cargo,
    NM_FUNCAO AS Funcao,
	CD_CBO02 AS CBO,
    VL_SALARI AS [Salario Funcio],
    NM_FILIAL AS Filial,
    NM_DEPTO AS Depto,
	VL_DEPEND AS [Dependentes],
    CP_FUNCIO AS CPF_PURO
FROM TB_DIM_FUNCIO
INNER JOIN TB_DIM_DEPTO ON CE_DEPRTO = ID_REGDPT
INNER JOIN TB_DIM_CARGO ON CE_CARGO = ID_REGCAR
INNER JOIN TB_DIM_FILIAL ON CE_FILIAL = ID_REGFIL
INNER JOIN TB_DIM_FUNCAO ON CE_FUNCAO = ID_REGFNC
INNER JOIN TB_DIM_SITFOL ON CE_SITFOL = ID_REGSFL
INNER JOIN TB_FAT_SALFUN ON CE_FUNCIO = CP_FUNCIO
WHERE
    TB_FAT_SALFUN.VF_REGVAL = 1 AND
    TB_DIM_FUNCIO.VF_REGVAL = 1;


-- [MOD].VW_IRPF source

CREATE VIEW [MOD].[VW_IRPF]
AS
SELECT VL_INICIA AS [Valor Inicial], VL_FINAL AS [Valor Final], VL_ALIQU AS [Aliquota]
FROM TB_DIM_IMPPES
WHERE VF_REGVAL = 1 AND NM_IMPOST = 'IRPF';


-- [MOD].VW_VENDAS source

CREATE VIEW [MOD].[VW_VENDAS]
AS
SELECT
	ID_REGVEN AS [ID Venda],
	CE_CLIENT AS [CNPJ],
	(SELECT TOP 1 NM_PRODUT FROM TB_DIM_PRODUT WHERE CE_PRODUT = ID_REGPRD) AS Produto,
	(VL_VENDA * QT_VENDA) AS [Valor da Venda],
	FORMAT(CONVERT(date, DT_REGCRI), 'd', 'pt-br') AS [Data Venda],
	(SELECT CE_FUNCIO FROM TB_DIM_USUARIO WHERE CE_USUACR = ID_REGUSR) AS [CPF Vendedor]
FROM TB_FAT_VENDA VND
WHERE VND.VF_REGVAL = 1;


-- [MOD].VW_VENDAS_MES source

CREATE VIEW [MOD].[VW_VENDAS_MES]
AS
WITH VENDAS AS
(
    SELECT 
        CE_CLIENT AS [CNPJ],
        (SELECT TOP 1 NM_CLIENT FROM TB_DIM_CLIENT WHERE CE_CLIENT = CP_CLIENT) AS [Nome Cliente],
        (SELECT TOP 1 NM_PRODUT FROM TB_DIM_PRODUT WHERE CE_PRODUT = ID_REGPRD) AS Produto,
        (VL_VENDA * QT_VENDA) AS [Valor da Venda],
        FORMAT(CONVERT(date, DT_REGCRI), 'yyyy-MM') AS [Data Venda] 
    FROM TB_FAT_VENDA VND
    WHERE VND.VF_REGVAL = 1
)

SELECT [Nome Cliente], [Data Venda], SUM([Valor da Venda]) AS [Total Vendas]
FROM VENDAS
GROUP BY [Nome Cliente], [Data Venda];
